[rewrite_local]

^https:\/\/log-api\.pangolin-sdk-toutiao\.com\/service\/2\/app_log\/? url script-response-body https://raw.githubusercontent.com/hoseynwnw/xscript/refs/heads/main/block_all_sdk.js
^https:\/\/sentry\.banjixiaoguanjia\.com\/api\/2\/envelope\/? url script-response-body https://raw.githubusercontent.com/hoseynwnw/xscript/refs/heads/main/block_all_sdk.js
^https:\/\/(cnlogs\.umengcloud\.com|cnlogs\.umeng\.com)\/unify_logs url script-response-body https://raw.githubusercontent.com/hoseynwnw/xscript/refs/heads/main/block_all_sdk.js
^https:\/\/open\.e\.kuaishou\.com\/rest\/e\/v3\/open\/logBatch url script-response-body https://raw.githubusercontent.com/hoseynwnw/xscript/refs/heads/main/block_all_sdk.js
^https:\/\/sdk-track\.66mobi\.com\/sdk\/report\/its\.api url script-response-body https://raw.githubusercontent.com/hoseynwnw/xscript/refs/heads/main/block_all_sdk.js
^http:\/\/tracker\.yfanads\.com\/api\/v2\/ads\/batchUpload url script-response-body https://raw.githubusercontent.com/hoseynwnw/xscript/refs/heads/main/block_all_sdk.js
^http:\/\/inner\.baihemob\.com\/ad2 url script-response-body https://raw.githubusercontent.com/hoseynwnw/xscript/refs/heads/main/block_all_sdk.js
^https:\/\/log\.banjixiaoguanjia\.com\/alog url script-response-body https://raw.githubusercontent.com/hoseynwnw/xscript/refs/heads/main/block_all_sdk.js

[mitm]
hostname = *pangolin-sdk-toutiao.com, *banjixiaoguanjia.com, *umeng*, *kuaishou.com, *66mobi.com, *yfanads.com, *baihemob.com


