[rewrite_local]
# 匹配这三个需要修改 JSON 内容的接口
^https?:\/\/.*\.zuoyebang\.com\/(ksnapi\/article\/list|abengine\/api\/client|ksnapi\/knowledge\/ucenter) url script-response-body https://raw.githubusercontent.com/hoseynwnw/xscript/main/bang/bang.js

# 另外两个直接拦截的域名依然建议用 reject-200（性能最好）
^https?:\/\/adx\.zuoyebang\.com url reject-200
^https?:\/\/nlogtj\.zuoyebang\.cc url reject-200

[mitm]
hostname = *.zuoyebang.com, adx.zuoyebang.com, nlogtj.zuoyebang.cc
