[rewrite_local]
^https?:\/\/yujie\.zuoyebang\.com\/hegui\/api\/app\/zbk\/filter url script-response-body https://raw.githubusercontent.com/hoseynwn/xscript/main/zuoyebang_filter.js

[mitm]
hostname = yujie.zuoyebang.com
